### ISSUE TITLE
DSO website - Meta 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#115]
Goal: Launch a v2 of this page http://secretrobotron.github.io/digital-skills-observatory/ 
This is the BEST communication tool we have today, and it deserves some TLC.

Lead: @secretrobotron 

Meta: 
- [x] add a contact / team section for people to get in touch #116 
- [x] add introduction text #117
- [ ] create a Project page 
- [ ] create a research method page 
- [ ] publish our curriculum and hypothesis work

**Comment by secretrobotron** [comment]
Filed plan ticket here: https://github.com/MozillaFoundation/plan/issues/782

**Comment by secretrobotron** [comment]
@LauraReynal 

> publish our curriculum and hypothesis work

Beyond simply linking out to those google docs, maybe we should be turning them into quick webpages so they're more easily digestible where it will count (your suggestion, giving credit where due :smile:  :+1:).

If so, that can be a separate issue, perhaps.

**Comment by chanditome** [comment]
@LauraReynal @secretrobotron how about a **_Community Stories_** page? That'll be super fun to read.

**Comment by lauradereynal** [comment]
That's a great idea @chanditome - do you want to take the lead on such a page? 
I would love to see a draft of what the stories would look like.

**Comment by lauradereynal** [comment]
Thanks for updating our website @secretrobotron
