### ISSUE TITLE
Prototype 1 - Build Prototype 1 Alpha

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#174]
_Meta ticket. Will list individual features to check off here._
## P1
- [x] Build home screen (#196)
- [x] Build **Floating Action Button** (#177)
- [x] Create icon for **Floating Action Button** (#176)
- [x] Come up with a name (#175)
- [x] Draft content for icons and tutorials (#151)
- [x] Put APK somewhere that team of testers can access (#178)
- [ ] ~~Flesh out UI from Mockups provided.~~
- [x] Setup Google Analytics android SDK (#208)
- [x] Finish content for tutorials/quizzes/icons (#191)
### Tutorials
- [x] Build Tutorial listing (#202)
- [x] Build Tutorial flow (#203)
### Tutorial Quizzes
- [ ] ~~Add quiz functionality to tutorial list (#204)~~
- [ ] ~~Build quiz flow (#205)~~
### Icons
- [x] Build Icon list (#206)
- [ ] Build Icon quiz (#207)
### Suggested Topic
- [x] Capturing system information to suggest topics (#200)
- [x] Build suggested topic screens & flow (#201)
### ~~Screenshot Questions~~
- [ ] ~~Build screenshot tutorial (#197)~~
- [ ] ~~Build screenshot functionality (#198)~~
- [ ] ~~Build questions list (#199)~~

Follows from #154.

**Comment by secretrobotron** [comment]
Followup when @flukeout's wireframes are finalized (#153).

**Comment by secretrobotron** [comment]
@brianmwadime, let's fill this out with more features for which we can write tickets. That way, others can jump in, and we have a better idea of what needs to be built.

**Comment by brianmwadime** [comment]
Release **apks** shall be located here in the meantime:
[Mozilla DSO release log](https://github.com/iHub/Mozilla-DSO-Quiz-Application/releases)

**Comment by secretrobotron** [comment]
👍 lookin' SO good. Thanks @brianmwadime. Reviewing it now.

**Comment by secretrobotron** [comment]
Ok @brianmwadime! Went through the checklist and filed some bugs.

**Comment by brianmwadime** [comment]
Got them. Working through the items.

Brian Mwadime M.
Phone: +254728956895
Skype: brian.mwadime
Work: Web & Mobile software engineer
Personal E-Mail: brian.mwadime@gmail.com
Work E-mail : info@brianmwadime.com
Website(s): brianmwadime.com, f http://code-hive.netortunekidew.co.ke

**Comment by secretrobotron** [comment]
Removed Screenshot features from the list above

**Comment by secretrobotron** [comment]
Removed Tutorial Quiz features from the list above
