### ISSUE TITLE
[meta] Kick off ToDo list

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#2]
Pre-Orlando 
- [x] Make plan specific to community for 2016: #4
- [x] Make plan specific to interventions for 2016: #5
- [x] Make slide deck to communicate this stuff to MoFo/MoCo/Gates: #3
- [x] Reach out to Participation team
- [x] Reach out to Curriculum team 
- [ ] Figure out more details about how we do software 
- [x] Engage with community members in Kenya
- [x] Figure out collaboration process with DDD: #6
- [ ] Design communication plan: #7

**Comment by lauradereynal** [comment]
we can close this and track the 2 remaining issues in their own tickets.
