### ISSUE TITLE
QA Checklist for Jisort

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#215]
A checklist for making sure Jisort works alright before it's deployed. Please add items below!
# Checklist
## Installation
- [ ] Can install the app
## Opening the app
- [ ] FAB appears on phone boot
- [ ] Can open the app through the icon (as with all apps)
- [ ] Can open the app through the Floating Action Button
- [ ] Can move the FAB around the screen
## Tutorial list
- [ ] Can scroll through list of tutorials
- [ ] Can click on each item in the tutorial list and go to its tutorial
## Tutorials
- [ ] Can swipe through tutorial
- [ ] Can use arrow buttons at top of tutorial to move back and forth through tutorial
- [ ] Can clearly see and understand images in tutorial
- [ ] Can watch animated gifs in tutorials
- [ ] Can read text easily
## Icon List
- [ ] Can open the icon list
- [ ] Can tap each icon and see a description
- [ ] Can tap some icons and see a link to a tutorial (e.g. Wi-Fi)
## Icon Quiz
- [ ] Can open the icon quiz
## System Awareness
- [ ] Alerted when wifi is enabled/disabled.
- [ ] Alerted when location settings enabled/disabled.
- [ ] Alerted when storage is near full.
- [ ] Alerted when bluetooth is enabled/disabled.
- [ ] Alerted when battery level is low.

**Comment by secretrobotron** [comment]
Need to come up with a simple routine to make sure the system-level stuff rom #189 is working:
- Wifi/network states
- Location enabled
- Bluetooth state
- Battery level event
- Applications installed event
- Low storage event
- Boot completed (for restarting the chat head service)

@brianmwadime

**Comment by brianmwadime** [comment]
@secretrobotron for the system level stuff.

Wifi/network states - Disable/enable wifi and check app dashboard.
Location - Enable and check dashboard.
Boot complete - Reboot phone and check whether FAB is started.
Low storage - :) You'll have to fill the phone's storage for this event to fire.
Bluetooth state - Enable/disable bluetooth and vcheck app dashboard.
Battery level - This will kick in when battery level is low then check app dashboard as well.

**Comment by secretrobotron** [comment]
@brianmwadime can you let me know when the icon quiz is available in the app again so I can write that section in the list above?

**Comment by dobbz** [comment]
@secretrobotron would it possible to add phone make and model, 
if an item failed then the error message if applicable.

**Comment by secretrobotron** [comment]
@dobbz based on the [stats you gave us](https://github.com/MozillaFoundation/digital-skills-observatory/issues/179#issuecomment-221720388), I think it's wise to test on Vodafone, Tecno, Huawei, and Samsung, and on 4.4.2, 4.2.2, 4.4.4, 2.3.6, and 5.0.2. They made up the majority of phones/OSs.

#### Phones
- Vodafone: VF685, 4.4.2, 20
- TECNO: Y3S, 4.4.2, 15
- Huawei: HUAWEI Y330-U11, 4.2.2, 7
- Samsung: SM-J100H, 4.4.4, 5
- Huawei: HUAWEI Y330-U01, 4.2.2, 4

#### OSs
- 4.4.2: 70
- 4.2.2: 31
- 4.4.4: 8
- 2.3.6: 4
- 5.0.2: 4

**Comment by secretrobotron** [comment]
@dobbz actually, are you able to cross-check that ^^ with the phones in the experimental group?

**Comment by secretrobotron** [comment]
> make and model, error

Yeah, definitely include that in bugs as necessary.

**Comment by festolangat** [comment]
I test with wiko slide 2 n it is works perfectly. Vs 5.1

**Comment by secretrobotron** [comment]
Jisort has launched :).
