### ISSUE TITLE
[meta] Closing Field Trip #1

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#51]
Things we need to finish before leaving Kenya @secretrobotron @JoashMango @DuncanGW 
- [ ] #49 summary of the bootcamp learnings 
- [ ] #26 blog post 
- [x] Expenses and admin for volunteers
- [ ] Overall budget review
- [ ] Wrap up email / coms for the community #50 
- [ ] Update list of hypotheses with the new ideas #30 
- [x] Update project timeline 
- [x] Triage and upload photos and videos 
- [x] Send first reporting

**Comment by lauradereynal** [comment]
First reporting is created but not sent yet. needs input

**Comment by lauradereynal** [comment]
Closing. Does not make sense any more to have this meta ticket. Will track individual tasks
