### ISSUE TITLE
[meta] Intervention 1 MegaTicket™

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#98]
Let's get serious about designing and implementing our first intervention. Add to and check off items below when they need to get done. If there is an associated github issue, list is there too :dancer:.
## TODO
- [x] Pick hypotheses that will define the subject matter: #97
- [x] Design curriculum and corresponding workshop: #93 
- [x] Plan the event(s): #87
- [x] Plan to document it: #99
- [x] Run a pilot: #89
- [x] Do it!
## Path to Success

The overall plan is to get from **data/insight** to **hypothesis** to **intervention**. Here's how all of that fits together in my mind:
##### Content for the Intervention
1. Identify a hypothesis together
2. Sketch out a design brief that will turn the hypothesis into curriculum/software
3. Create a workshop using the design brief which will become the activity/content for the intervention
4. Run a pilot workshop to make sure things will run smoothly during actual interventions
##### Logistics for the Intervention
1. Identify a few places that the intervention could happen in each location
2. Contact whoever we need to in order to use whichever spaces we choose
3. Confirm and lock dates.
4. DO IT.
##### Doing the actual work

The DSO Community will be split up into teams to get us there. They are (TBC):
- **Curriculum**: Think about, design, and implement curriculum for interventions.
- **Software**: Think about, design, and implement software for interventions.
- **Analysis**: Discuss external research and data from the field to connect it to hypotheses/interventions.
- **Events**: Look after logistics for events in each location.
- **Community**: Make sure the whole DSO community is aligned.

Each team will meet regularly to work on tasks that will get us to their goal. **Feel free to use this space to define what those tasks are, and then create individual issues for them on github.**

**Comment by lauradereynal** [comment]
Thanks for the awesome work :smile: 
We are done intervention 1
